apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
spec:
  destination:
    name: ''
    namespace: hello-world-app-argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: charts
    repoURL: 'https://github.com/rasmusselsmark/hello-argocd-and-helm'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
